"""Curated CDD capabilities catalog for Document Workspace (DiligenceIQ-compatible ids).

Full live catalog is 200+; DW-1 ships a focused subset used by document-copilot
tasks and suggestion cards. Expand in DW-2/DW-4 as runners land.
"""

from __future__ import annotations

from typing import Any

# DiligenceIQ-compatible capability records (subset).
CAPABILITIES: list[dict[str, Any]] = [
    {
        "id": "mkt_marimekko_segments",
        "kind": "market",
        "section": "Market Dynamics & Opportunity",
        "exhibit": "marimekko",
        "description": "Marimekko: SAM by segment (width = share of SAM) × channel mix (height).",
        "src": "algo",
        "title": "Mkt Marimekko Segments",
        "blurb": "Marimekko: SAM by segment (width = share of SAM) × channel mix (height).",
        "method": "",
    },
    {
        "id": "mkt_size_vs_penetration_combo",
        "kind": "sizing",
        "section": "Market Dynamics & Opportunity",
        "exhibit": "combo",
        "description": "Combo: SAM $ bars (left) + penetration % line (right); line anchored to real revenue.",
        "src": "algo",
        "title": "Mkt Size Vs Penetration Combo",
        "blurb": "Combo: SAM $ bars (left) + penetration % line (right); line anchored to real revenue.",
        "method": "",
    },
    {
        "id": "gx_x_market_funnel",
        "kind": "sizing",
        "section": "Detailed Findings: Market Dynamics & Opportunity",
        "exhibit": "funnel",
        "description": "Market sizing funnel (TAM/SAM/SOM) from live web research",
        "src": "web",
        "title": "X Market Funnel",
        "blurb": "Market sizing funnel (TAM/SAM/SOM) from live web research",
        "method": "",
    },
    {
        "id": "gx_x_competitor_table",
        "kind": "benchmark",
        "section": "Detailed Findings: Competitive Landscape",
        "exhibit": "table",
        "description": "Competitive landscape evidence table (web)",
        "src": "web",
        "title": "X Competitor Table",
        "blurb": "Competitive landscape evidence table (web)",
        "method": "",
    },
    {
        "id": "gx_x_market_evidence",
        "kind": "benchmark",
        "section": "Detailed Findings: Market Dynamics & Opportunity",
        "exhibit": "table",
        "description": "Cited live-research market evidence table",
        "src": "web",
        "title": "X Market Evidence",
        "blurb": "Cited live-research market evidence table",
        "method": "",
    },
    {
        "id": "growth_trend",
        "kind": "trend",
        "section": "Detailed Findings: Financial Profile",
        "exhibit": "bar_chart",
        "description": "Compounding/growth of any monetary level metric (CAGR + forecast).",
        "src": "algo",
        "title": "Growth Trend",
        "blurb": "This tool shows the growth rate of a company's financial metrics over time.",
        "method": "It takes the first and last year, finds the steady yearly percent that links them.",
    },
    {
        "id": "kpi_scorecard",
        "kind": "scorecard",
        "section": "Investment Highlights",
        "exhibit": "stat_callout",
        "description": "Headline KPI scorecard (latest-year metrics as stat callouts).",
        "src": "algo",
        "title": "Key Performance",
        "blurb": "This tool shows a company's key performance indicators.",
        "method": "It gathers data on the company's performance metrics and displays them clearly.",
    },
    {
        "id": "investment_thesis",
        "kind": "narrative",
        "section": "Investment Highlights",
        "exhibit": "table",
        "description": "Four-pillar investment thesis table - composes computed proof-points into the argued case.",
        "src": "algo",
        "title": "Investment Thesis",
        "blurb": "This tool shows the investment case for a company.",
        "method": "It takes the computed proof points and composes them into a four-pillar thesis table.",
    },
    {
        "id": "risk_assessment",
        "kind": "risk",
        "section": "Market Dynamics & Opportunity",
        "exhibit": "gauges",
        "description": "Thesis-risk severity gauges - carries each structural risk to an evidence-derived severity + mitigant.",
        "src": "algo",
        "title": "Risk Assessment",
        "blurb": "Thesis-risk severity gauges with evidence-derived severity + mitigant.",
        "method": "",
    },
    {
        "id": "margin_bridge",
        "kind": "margin",
        "section": "Detailed Findings: Financial Profile",
        "exhibit": "grouped_bar",
        "description": "Margin profile (gross + EBITDA margin) expansion over time.",
        "src": "algo",
        "title": "Profit Margin",
        "blurb": "This tool shows a company's profit margin over time.",
        "method": "It calculates the difference between revenue and costs as a percentage of revenue.",
    },
    {
        "id": "gx_yoy_scorecard",
        "kind": "summary",
        "section": "Detailed Findings: Financial Profile",
        "exhibit": "stat_callout",
        "description": "Latest-year headline P&L (revenue, gross profit, EBITDA, net profit) with YoY deltas.",
        "src": "algo",
        "title": "Year Over Year Growth",
        "blurb": "This tool shows a company's year over year growth in revenue and profit.",
        "method": "It calculates YoY growth by comparing current and prior year values.",
    },
    {
        "id": "gen_geographic_mix",
        "kind": "market",
        "section": "Detailed Findings: Business Introduction & Market Primer",
        "exhibit": "donut",
        "description": "Geographic revenue mix and international headroom - any sector.",
        "src": "algo",
        "title": "Geographic Revenue Mix",
        "blurb": "This tool shows the mix of revenue from different geographic regions.",
        "method": "It categorizes revenue by region and calculates each region's share.",
    },
    {
        "id": "cmp_positioning_scatter",
        "kind": "benchmark",
        "section": "Detailed Findings: Competitive Landscape",
        "exhibit": "scatter",
        "description": "Competitive positioning scatter: x=Vertical specialisation, y=VAS depth/flexibility.",
        "src": "web",
        "title": "Competitive Positioning",
        "blurb": "This tool shows the competitive positioning scatter plot.",
        "method": "It plots players by vertical specialisation and capability depth.",
    },
    {
        "id": "narr_investment_summary",
        "kind": "narrative",
        "section": "Investment Highlights",
        "exhibit": "exec_bullets",
        "description": "Headline investment case - 5 bullets anchored by VDR-derived numbers.",
        "src": "algo",
        "title": "Investment Case",
        "blurb": "This tool shows the headline investment case for a company.",
        "method": "It analyzes VDR-derived numbers and identifies key investment opportunities.",
    },
    {
        "id": "narr_risks_mitigants",
        "kind": "narrative",
        "section": "Investment Highlights",
        "exhibit": "exec_bullets",
        "description": "Key risks and mitigants - 2-column Risk / Mitigant layout.",
        "src": "algo",
        "title": "Risk Management",
        "blurb": "This tool shows the key risks and mitigants for a company.",
        "method": "It identifies potential risks and strategies to mitigate them.",
    },
    {
        "id": "gx_x_kpi_grid",
        "kind": "mix",
        "section": "Investment Highlights",
        "exhibit": "stat_callout",
        "description": "Headline operating KPI scorecard from any data-room metrics",
        "src": "algo",
        "title": "X KPI Grid",
        "blurb": "Headline operating KPI scorecard from any data-room metrics",
        "method": "",
    },
    {
        "id": "gx_cagr_momentum",
        "kind": "trend",
        "section": "Investment Highlights",
        "exhibit": "hbar",
        "description": "Ranked CAGR across the key VDR metrics (growth-momentum bar).",
        "src": "algo",
        "title": "CAGR Momentum Analysis",
        "blurb": "This tool shows the compound annual growth rate of key metrics.",
        "method": "It computes CAGR by comparing values across the period.",
    },
    {
        "id": "mkt_tam_sam_ovals",
        "kind": "sizing",
        "section": "Market Dynamics & Opportunity",
        "exhibit": "nested_ovals",
        "description": "Concentric TAM/SAM/Served rings; served anchored to net revenue, TAM/SAM grossed up.",
        "src": "algo",
        "title": "Mkt TAM SAM Ovals",
        "blurb": "Concentric TAM/SAM/Served rings; served anchored to net revenue.",
        "method": "",
    },
    {
        "id": "ma_precedent_transactions",
        "kind": "m&a",
        "section": "Detailed Findings: Growth Opportunities",
        "exhibit": "table",
        "description": "Real publicly-announced precedent transactions as a comparable set.",
        "src": "web",
        "title": "M&A Precedents",
        "blurb": "This tool shows historical M&A activity in the industry.",
        "method": "It plots publicly announced M&A data as a comparable set.",
    },
    {
        "id": "implied_valuation",
        "kind": "valuation",
        "section": "Investment Highlights",
        "exhibit": "hbar",
        "description": "Indicative EV range from stated sector multiples × real FY revenue/EBITDA.",
        "src": "illustrative",
        "title": "Implied Valuation",
        "blurb": "This tool shows the potential valuation of a company.",
        "method": "It applies sector multiples to historical financial data.",
    },
    {
        "id": "section_dashboard",
        "kind": "composite",
        "section": "Investment Highlights",
        "exhibit": "composite",
        "description": "Combine a section's algo exhibits into one dense multi-exhibit dashboard page.",
        "src": "algo",
        "title": "Dashboard Summary",
        "blurb": "This tool shows a combined view of key exhibits and metrics.",
        "method": "It organizes section exhibits into a KPI strip plus coordinated exhibits.",
    },
]


def list_capabilities() -> list[dict[str, Any]]:
    return [dict(c) for c in CAPABILITIES]


def capability_by_id(cap_id: str) -> dict[str, Any] | None:
    for cap in CAPABILITIES:
        if cap["id"] == cap_id:
            return dict(cap)
    return None
