"""Fixed 32-requirement CDD evidence catalog (DiligenceIQ-identical)."""

from __future__ import annotations

WORKSTREAMS: list[dict] = [
    {
        "id": "primer",
        "label": "Company & Financials",
        "desc": "The Target's model, scale, trajectory, and track record.",
    },
    {
        "id": "market",
        "label": "Market Dynamics",
        "desc": "How big, how fast-growing, how resilient the market is.",
    },
    {
        "id": "decision",
        "label": "Decision-Making",
        "desc": "How buyers actually switch and decide.",
    },
    {
        "id": "feedback",
        "label": "Customer Feedback",
        "desc": "Whether customers are satisfied and will stay.",
    },
    {
        "id": "competitive",
        "label": "Competitive Positioning",
        "desc": "Whether the Target can win against the alternatives.",
    },
    {
        "id": "growth",
        "label": "Growth Opportunities",
        "desc": "Whether the growth levers are real and reachable.",
    },
]

REQUIREMENTS: list[dict] = [
    {
        "id": "fin_history",
        "label": "Financial history (revenue / profit)",
        "ws": "primer",
        "data_class": "vdr",
        "weight": 3,
        "so_what": "Establishes scale and trajectory in one place.",
        "strong": ["financial", "fdd", "revenue", "profit", "executive", "valuation", "income"],
        "weak": ["cim", "overview", "commercial"],
    },
    {
        "id": "unit_econ",
        "label": "Unit economics / take rate / margin",
        "ws": "primer",
        "data_class": "vdr",
        "weight": 2,
        "so_what": "Shows whether provider economics hold or improve.",
        "strong": ["unit econ", "take rate", "gross margin"],
        "weak": ["financial", "operational", "commercial", "margin", "economics"],
    },
    {
        "id": "segment_mix",
        "label": "Segment / go-to-market mix",
        "ws": "primer",
        "data_class": "vdr",
        "weight": 2,
        "so_what": "Locates where revenue comes from and where it is shifting.",
        "strong": ["segment mix", "go to market", "gtm"],
        "weak": ["commercial", "corporate", "market", "segment"],
    },
    {
        "id": "cust_kpis",
        "label": "Customer KPIs (counts, retention, churn)",
        "ws": "primer",
        "data_class": "vdr",
        "weight": 3,
        "so_what": "The base's health: growth, retention, and attrition.",
        "strong": ["churn", "nps", "retention kpi", "customer kpi"],
        "weak": ["customer", "retention", "hr", "organizational", "commercial"],
    },
    {
        "id": "ma_track",
        "label": "M&A / acquisition track record",
        "ws": "primer",
        "data_class": "vdr",
        "weight": 1,
        "so_what": "Underwrites the forward M&A thesis from evidence.",
        "strong": ["acquisition track", "buy-side", "closed acquisitions"],
        "weak": ["acquisition", "comparable", "valuation", "investment"],
    },
    {
        "id": "roadmap",
        "label": "Product roadmap (labelled as plans)",
        "ws": "primer",
        "data_class": "vdr",
        "weight": 1,
        "so_what": "Shows platform evolution; must be labelled plan, not current state.",
        "strong": ["product roadmap", "roadmap"],
        "weak": ["technical", "product", "operational"],
    },
    {
        "id": "market_size",
        "label": "Market size (TAM / SAM / served)",
        "ws": "market",
        "data_class": "web",
        "weight": 3,
        "so_what": "Establishes the headline opportunity.",
        "strong": ["tam", "sam", "market size"],
        "weak": ["market", "commercial", "competition"],
    },
    {
        "id": "growth_drivers",
        "label": "Market growth drivers",
        "ws": "market",
        "data_class": "web",
        "weight": 2,
        "so_what": "Decomposes growth into interrogable levers.",
        "strong": ["growth driver", "cagr"],
        "weak": ["market", "commercial", "competition"],
    },
    {
        "id": "resilience",
        "label": "Downturn / recession resilience",
        "ws": "market",
        "data_class": "web",
        "weight": 1,
        "so_what": "Proves the market grows through downturns.",
        "strong": ["recession", "downturn", "resilience"],
        "weak": ["market", "commercial", "competition"],
    },
    {
        "id": "vas_opportunity",
        "label": "Value-added / adjacent opportunity",
        "ws": "market",
        "data_class": "web",
        "weight": 1,
        "so_what": "Sizes the attach opportunity beyond the core.",
        "strong": ["value added", "vas", "adjacent"],
        "weak": ["market", "commercial", "competition"],
    },
    {
        "id": "switch_lifecycle",
        "label": "Switching triggers & lifecycle",
        "ws": "decision",
        "data_class": "primary",
        "weight": 2,
        "so_what": "Locates the window when providers get switched.",
        "strong": [],
        "weak": ["commercial", "customer", "switch"],
    },
    {
        "id": "decision_process",
        "label": "Decision process & stakeholders",
        "ws": "decision",
        "data_class": "primary",
        "weight": 2,
        "so_what": "Who is in the room and how they decide, by segment.",
        "strong": [],
        "weak": ["commercial", "customer", "stakeholder"],
    },
    {
        "id": "purchase_criteria",
        "label": "Purchase criteria & weights",
        "ws": "decision",
        "data_class": "primary",
        "weight": 3,
        "so_what": "What buyers weigh — the axes deals are won on.",
        "strong": [],
        "weak": ["commercial", "customer", "criteria"],
    },
    {
        "id": "switch_friction",
        "label": "Switching complexity / friction",
        "ws": "decision",
        "data_class": "primary",
        "weight": 2,
        "so_what": "Grades the friction that gates every deal.",
        "strong": [],
        "weak": ["commercial", "customer", "friction"],
    },
    {
        "id": "satisfaction",
        "label": "Satisfaction / NPS",
        "ws": "feedback",
        "data_class": "primary",
        "weight": 3,
        "so_what": "Advocacy is measured, not inferred.",
        "strong": ["nps", "csat"],
        "weak": ["customer", "commercial", "satisfaction"],
    },
    {
        "id": "strengths",
        "label": "Strengths — customer evidence",
        "ws": "feedback",
        "data_class": "primary",
        "weight": 2,
        "so_what": "Drivers of loyalty in customers' own words.",
        "strong": [],
        "weak": ["customer", "commercial", "strength"],
    },
    {
        "id": "dev_areas",
        "label": "Development areas — customer evidence",
        "ws": "feedback",
        "data_class": "primary",
        "weight": 2,
        "so_what": "Honest improvement areas — credibility currency.",
        "strong": [],
        "weak": ["customer", "commercial", "development"],
    },
    {
        "id": "churn_triggers",
        "label": "Churn triggers (beyond price)",
        "ws": "feedback",
        "data_class": "primary",
        "weight": 2,
        "so_what": "Why customers actually leave, ranked.",
        "strong": ["churn"],
        "weak": ["customer", "commercial", "retention"],
    },
    {
        "id": "landscape",
        "label": "Competitor landscape / archetypes",
        "ws": "competitive",
        "data_class": "web",
        "weight": 2,
        "so_what": "Who the Target meets in each route to market.",
        "strong": ["competitor landscape", "competitive landscape"],
        "weak": ["market", "competition", "competitive"],
    },
    {
        "id": "price_bench",
        "label": "Price benchmarking",
        "ws": "competitive",
        "data_class": "web",
        "weight": 2,
        "so_what": "Effective pricing across providers, comparably.",
        "strong": ["price bench", "pricing bench"],
        "weak": ["valuation", "comparable", "price"],
    },
    {
        "id": "criteria_perf",
        "label": "Criteria performance vs archetypes",
        "ws": "competitive",
        "data_class": "primary",
        "weight": 2,
        "so_what": "Scores the Target vs alternatives on each criterion.",
        "strong": [],
        "weak": ["competition", "commercial", "criteria"],
    },
    {
        "id": "feature_bench",
        "label": "Feature / module benchmarking",
        "ws": "competitive",
        "data_class": "primary",
        "weight": 1,
        "so_what": "Satisfaction with specific modules by provider.",
        "strong": [],
        "weak": ["competition", "commercial", "technical"],
    },
    {
        "id": "nps_by_provider",
        "label": "NPS by provider type",
        "ws": "competitive",
        "data_class": "primary",
        "weight": 1,
        "so_what": "Advocacy gaps reveal switching potential.",
        "strong": ["nps"],
        "weak": ["provider nps"],
    },
    {
        "id": "painpoints",
        "label": "Competitor pain-point synthesis",
        "ws": "competitive",
        "data_class": "primary",
        "weight": 2,
        "so_what": "The structural complaints the Target attacks.",
        "strong": [],
        "weak": ["competition", "commercial", "pain"],
    },
    {
        "id": "wtp",
        "label": "Willingness to pay / full-suite demand",
        "ws": "competitive",
        "data_class": "primary",
        "weight": 2,
        "so_what": "Whether the market wants (and will pay for) the model.",
        "strong": ["willingness to pay", "wtp"],
        "weak": ["competition", "commercial", "demand"],
    },
    {
        "id": "levers_overview",
        "label": "Growth-lever agenda",
        "ws": "growth",
        "data_class": "vdr",
        "weight": 1,
        "so_what": "The sequenced set of levers the chapter proves.",
        "strong": ["growth lever", "growth agenda", "growth plan"],
        "weak": ["growth lever", "value creation plan"],
    },
    {
        "id": "contestable_pool",
        "label": "Contestable / new-customer pool",
        "ws": "growth",
        "data_class": "web",
        "weight": 2,
        "so_what": "The annually winnable spend.",
        "strong": ["contestable", "winnable spend", "new customer pool"],
        "weak": ["contestable", "white space pool"],
    },
    {
        "id": "partner_whitespace",
        "label": "Partner / channel whitespace",
        "ws": "growth",
        "data_class": "web",
        "weight": 1,
        "so_what": "Unpenetrated partner cells worth the most.",
        "strong": ["channel whitespace", "partner whitespace"],
        "weak": ["partner", "channel", "market", "manufacturing", "supply"],
    },
    {
        "id": "partner_willingness",
        "label": "Partner adoption willingness",
        "ws": "growth",
        "data_class": "primary",
        "weight": 2,
        "so_what": "Shows the whitespace is willing, not just present.",
        "strong": ["partner adoption"],
        "weak": ["partner willingness", "channel adoption"],
    },
    {
        "id": "pricing_elasticity",
        "label": "Pricing optimization / elasticity",
        "ws": "growth",
        "data_class": "primary",
        "weight": 1,
        "so_what": "Whether the market absorbs price moves.",
        "strong": ["elasticity"],
        "weak": ["price", "valuation", "comparable"],
    },
    {
        "id": "adjacencies",
        "label": "Adjacent-segment expansion",
        "ws": "growth",
        "data_class": "web",
        "weight": 1,
        "so_what": "Sizes adjacencies and carry-over capabilities.",
        "strong": ["adjacency", "adjacent segment"],
        "weak": ["adjacent", "market", "commercial"],
    },
    {
        "id": "fwd_ma",
        "label": "Strategic M&A pipeline",
        "ws": "growth",
        "data_class": "vdr",
        "weight": 1,
        "so_what": "Forward acquisition thesis from track record.",
        "strong": ["m&a pipeline", "acquisition pipeline", "target list"],
        "weak": ["strategic pipeline", "bolt-on pipeline"],
    },
]

STATUS_LEGEND: dict[str, dict[str, str]] = {
    "have": {
        "label": "In data room",
        "color": "#5E7C63",
        "remedy": "Covered by uploaded documents.",
    },
    "partial": {
        "label": "Partial",
        "color": "#B08A4E",
        "remedy": "Some signal in the data room — request the complete dataset.",
    },
    "web": {
        "label": "Web-fillable",
        "color": "#5C7A99",
        "remedy": "Not in the data room; fillable by secondary (web) research.",
    },
    "request_vdr": {
        "label": "Request from mgmt",
        "color": "#94908A",
        "remedy": "Should exist in a data room; ask management to provide.",
    },
    "primary": {
        "label": "Primary research",
        "color": "#A85A4C",
        "remedy": "Only obtainable via interviews + survey fieldwork.",
    },
}

STATUS_CREDIT = {
    "have": 1.0,
    "partial": 0.5,
    "web": 0.15,
    "request_vdr": 0.0,
    "primary": 0.0,
}

EMPTY_ROLL = {"have": 0, "partial": 0, "web": 0, "request_vdr": 0, "primary": 0}

DATA_CLASS_LABEL = {"vdr": "Data room", "web": "Web", "primary": "Primary"}

SCORED_STATUSES = frozenset(STATUS_LEGEND)
WORKSTREAM_IDS = frozenset(ws["id"] for ws in WORKSTREAMS)


def validate_catalog() -> None:
    """Fail fast if a requirement points at an unknown workstream or data class."""
    for req in REQUIREMENTS:
        req_id = req.get("id", "<missing>")
        ws = req.get("ws")
        data_class = req.get("data_class")
        if ws not in WORKSTREAM_IDS:
            raise ValueError(f"Requirement {req_id} has unknown workstream {ws!r}")
        if data_class not in DATA_CLASS_LABEL:
            raise ValueError(f"Requirement {req_id} has unknown data_class {data_class!r}")


validate_catalog()
